// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckConnection'](arg1, arg2, arg3);
}

export function CreateBazaar(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateBazaar'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SendDonation(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDonation'](arg1, arg2, arg3);
}

export function VendorExistsCheck(arg1, arg2) {
  return window['go']['main']['App']['VendorExistsCheck'](arg1, arg2);
}
