// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckConnection'](arg1, arg2, arg3);
}

export function CreateBazaar() {
  return window['go']['main']['App']['CreateBazaar']();
}

export function SendDonation(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDonation'](arg1, arg2, arg3);
}
